import type { PropsWithChildren } from 'react'
import { Camera, Controls, Environment, Light, Lighting, Shadows, SceneFog, GroundGrid, RenderSettings, Effect, postFXCatalog, defs, type LightProps } from '@artinos/modules'
import { useResolvedParameter } from '@artinos/runtime'

const useParameter=<T extends import('@artinos/runtime').ParameterValue>(definition:import('@artinos/runtime').ParameterDefinition<T>):[T,never]=>[useResolvedParameter(definition,100),undefined as never]

export function RuntimeStage({children}:PropsWithChildren){
 const[environment]=useParameter(defs.environment),[envIntensity]=useParameter(defs.environmentIntensity),[envBlur]=useParameter(defs.environmentBlur),[envRotation]=useParameter(defs.environmentRotation),[hdr]=useParameter(defs.hdr),[backgroundMode]=useParameter(defs.backgroundMode),[backgroundColor]=useParameter(defs.backgroundColor),[ground]=useParameter(defs.ground),[groundColor]=useParameter(defs.groundColor),[groundY]=useParameter(defs.groundY)
 const[cameraMode]=useParameter(defs.cameraMode),[cameraPreset]=useParameter(defs.cameraPreset),[cameraTarget]=useParameter(defs.cameraTarget),[fov]=useParameter(defs.fov),[lens]=useParameter(defs.lens),[filmGauge]=useParameter(defs.filmGauge),[cameraZoom]=useParameter(defs.cameraZoom),[cameraNear]=useParameter(defs.cameraNear),[cameraFar]=useParameter(defs.cameraFar),[cameraFit]=useParameter(defs.cameraFit),[cameraFitMargin]=useParameter(defs.cameraFitMargin),[cameraTransition]=useParameter(defs.cameraTransition),[cameraUpdateRate]=useParameter(defs.cameraUpdateRate)
 const[controls]=useParameter(defs.controls),[controlDamping]=useParameter(defs.controlDamping),[controlDampingFactor]=useParameter(defs.controlDampingFactor),[autoRotate]=useParameter(defs.autoRotate),[autoRotateSpeed]=useParameter(defs.autoRotateSpeed),[minDistance]=useParameter(defs.minDistance),[maxDistance]=useParameter(defs.maxDistance),[enablePan]=useParameter(defs.enablePan),[enableZoom]=useParameter(defs.enableZoom),[enableRotate]=useParameter(defs.enableRotate)
 const[lighting]=useParameter(defs.lighting),[lightIntensity]=useParameter(defs.lightIntensity),[lightKey]=useParameter(defs.lightKey),[lightFill]=useParameter(defs.lightFill),[lightRim]=useParameter(defs.lightRim),[temp]=useParameter(defs.lightTemperature),[lightColor]=useParameter(defs.lightColor),[lightShadowMap]=useParameter(defs.lightShadowMap),[customLights]=useParameter(defs.customLights)
 const[shadows]=useParameter(defs.shadows),[shadowOpacity]=useParameter(defs.shadowOpacity),[shadowBlur]=useParameter(defs.shadowBlur),[shadowSize]=useParameter(defs.shadowSize),[shadowFar]=useParameter(defs.shadowFar),[shadowSamples]=useParameter(defs.shadowSamples),[shadowFocus]=useParameter(defs.shadowFocus),[shadowColor]=useParameter(defs.shadowColor)
 const[fog]=useParameter(defs.fog),[fogColor]=useParameter(defs.fogColor),[fogNear]=useParameter(defs.fogNear),[fogFar]=useParameter(defs.fogFar),[fogDensity]=useParameter(defs.fogDensity),[grid]=useParameter(defs.grid),[gridSize]=useParameter(defs.gridSize),[gridDivisions]=useParameter(defs.gridDivisions),[gridColor]=useParameter(defs.gridColor),[gridSectionColor]=useParameter(defs.gridSectionColor),[gridFade]=useParameter(defs.gridFade)
 const[renderPreset]=useParameter(defs.renderPreset),[shadowMap]=useParameter(defs.shadowMap),[toneMapping]=useParameter(defs.toneMapping),[outputColorSpace]=useParameter(defs.outputColorSpace),[exposure]=useParameter(defs.exposure),[clearAlpha]=useParameter(defs.clearAlpha),[postfxEnabled]=useParameter(defs.postfxEnabled)
 const background=backgroundMode==='color'?String(backgroundColor):backgroundMode==='transparent'?false:true
 return <><Environment preset={environment as any} background={background} intensity={Number(envIntensity)} blur={Number(envBlur)} rotation={Number(envRotation)} hdr={String(hdr)||undefined} ground={Boolean(ground)} groundColor={String(groundColor)} groundY={Number(groundY)}/><Camera mode={cameraMode as any} preset={cameraPreset as any} target={cameraTarget as [number,number,number]} fov={Number(fov)} lens={Number(lens)>0?Number(lens):undefined} filmGauge={Number(filmGauge)} zoom={Number(cameraZoom)} near={Number(cameraNear)} far={Number(cameraFar)} fit={Boolean(cameraFit)} fitMargin={Number(cameraFitMargin)} transition={Number(cameraTransition)} updateRate={Number(cameraUpdateRate)}/><Controls mode={controls as any} damping={Boolean(controlDamping)} dampingFactor={Number(controlDampingFactor)} autoRotate={Boolean(autoRotate)} autoRotateSpeed={Number(autoRotateSpeed)} minDistance={Number(minDistance)} maxDistance={Number(maxDistance)} enablePan={Boolean(enablePan)} enableZoom={Boolean(enableZoom)} enableRotate={Boolean(enableRotate)}/><Lighting preset={lighting as any} intensity={Number(lightIntensity)} keyIntensity={Number(lightKey)} fill={Number(lightFill)} rim={Number(lightRim)} temperature={Number(temp)} color={String(lightColor)==='#ffffff'?undefined:String(lightColor)} shadowMapSize={Number(lightShadowMap)} shadows={shadows!=='off'}/><CustomLights json={String(customLights)}/><Shadows preset={shadows as any} opacity={Number(shadowOpacity)} blur={Number(shadowBlur)} size={Number(shadowSize)} far={Number(shadowFar)} samples={Number(shadowSamples)} focus={Number(shadowFocus)} color={String(shadowColor)}/><SceneFog mode={fog as any} color={String(fogColor)} near={Number(fogNear)} far={Number(fogFar)} density={Number(fogDensity)}/><GroundGrid enabled={Boolean(grid)} size={Number(gridSize)} divisions={Number(gridDivisions)} color={String(gridColor)} sectionColor={String(gridSectionColor)} fadeDistance={Number(gridFade)} y={Number(groundY)}/><RenderSettings preset={renderPreset as any} exposure={Number(exposure)} toneMapping={toneMapping as any} shadowMap={shadowMap as any} outputColorSpace={outputColorSpace as any} clearAlpha={Number(clearAlpha)} shadows={shadows!=='off'}/>{children}{Boolean(postfxEnabled)&&postFXCatalog.map(entry=><EffectFromParameters key={entry.type} type={entry.type}/>)}</>
}
function EffectFromParameters({type}:{type:(typeof postFXCatalog)[number]['type']}){
 const entry=postFXCatalog.find(e=>e.type===type)!;
 const[enabled]=useParameter({id:`postfx.${type}.enabled`,label:`${entry.label} Enabled`,type:'boolean',defaultValue:['bloom','vignette','fxaa'].includes(type),group:`PostFX / ${entry.label}`} as any);
 const[order]=useParameter({id:`postfx.${type}.order`,label:'Order',type:'number',defaultValue:(postFXCatalog.indexOf(entry)+1)*100,min:0,max:5000,step:10,group:`PostFX / ${entry.label}`,advanced:true} as any);
 // Every catalog entry mounts, but a disabled effect's parameters are worth nothing: EffectParams
 // recurses one component (and one subscription) per param, so reading them for the ~41 effects
 // that are off by default cost ~55 idle subscriptions and re-rendered the whole stage on any
 // parameter write. The Effect still registers so ordering and enable/disable stay identical.
 if(!enabled)return <Effect id={`project.${entry.type}`} type={entry.type} enabled={false} order={Number(order)} params={{}}/>;
 return <EffectParams entry={entry} enabled order={Number(order)} index={0} params={{}}/>
}
function EffectParams({entry,enabled,order,index,params}:{entry:(typeof postFXCatalog)[number];enabled:boolean;order:number;index:number;params:Record<string,number|boolean>}):any{if(index>=entry.params.length)return <Effect id={`project.${entry.type}`} type={entry.type} enabled={enabled} order={order} params={params}/>;const p=entry.params[index];return <ParameterRead definition={{id:`postfx.${entry.type}.${p.key}`,label:p.label,type:p.type,defaultValue:p.defaultValue,min:p.min,max:p.max,step:p.step,group:`PostFX / ${entry.label}`} as any}>{value=><EffectParams entry={entry} enabled={enabled} order={order} index={index+1} params={{...params,[p.key]:value as any}}/>}</ParameterRead>}
function ParameterRead({definition,children}:{definition:any;children:(value:any)=>any}){const[value]=useParameter(definition);return children(value)}

function CustomLights({json}:{json:string}){let lights:Array<LightProps&{id?:string}>=[];try{const parsed=JSON.parse(json);if(Array.isArray(parsed))lights=parsed}catch{/* invalid edits are ignored until valid JSON is restored */}return <>{lights.map((light,index)=><Light key={light.id??index} {...light}/>)}</>}
