/// <reference lib="webworker" />
import { FaceLandmarker, FilesetResolver, GestureRecognizer, HandLandmarker, ObjectDetector, PoseLandmarker } from '@mediapipe/tasks-vision'
import type { Landmark, VisionFrameResult, VisionWorkerRequest, VisionWorkerResponse } from './vision-protocol'

const context=self as DedicatedWorkerGlobalScope,tasks:Record<string,any>={}
const pack=(points:any[]=[]):Landmark[]=>points.map(point=>[point.x,point.y,point.z??0,point.visibility])
const createFileset=async(wasmPath:string)=>{const suffix=await FilesetResolver.isSimdSupported()?'':'_nosimd',loader=`${wasmPath}/vision_wasm${suffix}_internal.js`,wasm=`${wasmPath}/vision_wasm${suffix}_internal.wasm`,source=await fetch(loader).then(response=>{if(!response.ok)throw new Error(`MediaPipe loader ${response.status}`);return response.text()});(context as any).ModuleFactory=(0,eval)(`(()=>{${source};return ModuleFactory})()\n//# sourceURL=${loader}`);return{wasmLoaderPath:'',wasmBinaryPath:wasm}}
context.onmessage=async(event:MessageEvent<VisionWorkerRequest>)=>{const message=event.data;try{if(message.type==='init'){const resolver=()=>createFileset(message.wasmPath),base=(modelAssetPath:string)=>({baseOptions:{modelAssetPath},runningMode:'VIDEO' as const});if(message.features.includes('hands')&&message.models.hands)tasks.hands=await HandLandmarker.createFromOptions(await resolver(),{...base(message.models.hands),numHands:2});if(message.features.includes('face')&&message.models.face)tasks.face=await FaceLandmarker.createFromOptions(await resolver(),{...base(message.models.face),numFaces:1,outputFaceBlendshapes:true});if(message.features.includes('pose')&&message.models.pose)tasks.pose=await PoseLandmarker.createFromOptions(await resolver(),{...base(message.models.pose),numPoses:1});if(message.features.includes('gestures')&&message.models.gestures)tasks.gestures=await GestureRecognizer.createFromOptions(await resolver(),{...base(message.models.gestures),numHands:2});if(message.features.includes('objects')&&message.models.objects)tasks.objects=await ObjectDetector.createFromOptions(await resolver(),{...base(message.models.objects)});post({type:'ready'});return}if(message.type==='dispose'){for(const task of Object.values(tasks))task.close?.();post({type:'disposed'});context.close();return}const started=performance.now(),timestamp=message.timestamp,hands=tasks.hands?.detectForVideo(message.bitmap,timestamp),face=tasks.face?.detectForVideo(message.bitmap,timestamp),pose=tasks.pose?.detectForVideo(message.bitmap,timestamp),gestures=tasks.gestures?.recognizeForVideo(message.bitmap,timestamp),objects=tasks.objects?.detectForVideo(message.bitmap,timestamp);const result:VisionFrameResult={frameId:message.frameId,timestamp,inferenceMs:performance.now()-started,hands:(hands?.landmarks??[]).map((points:any[],index:number)=>({landmarks:pack(points),world:pack(hands?.worldLandmarks?.[index]),handedness:hands?.handedness?.[index]?.[0]?.categoryName?.toLowerCase?.()??`hand${index}`})),faces:(face?.faceLandmarks??[]).map(pack),poses:(pose?.landmarks??[]).map(pack),gestures:(gestures?.gestures??[]).flatMap((items:any[],index:number)=>items.slice(0,1).map(item=>({name:item.categoryName,score:item.score,handedness:gestures?.handedness?.[index]?.[0]?.categoryName}))),objects:(objects?.detections??[]).map((item:any)=>({label:item.categories?.[0]?.categoryName??'object',score:item.categories?.[0]?.score??0,box:item.boundingBox?[item.boundingBox.originX,item.boundingBox.originY,item.boundingBox.width,item.boundingBox.height]:undefined}))};post({type:'result',result})}catch(error){post({type:'error',message:error instanceof Error?error.message:String(error),frameId:message.type==='frame'?message.frameId:undefined})}finally{if(message.type==='frame')message.bitmap.close()}}
function post(message:VisionWorkerResponse){context.postMessage(message)}
