import type { PostFXType } from './effect'
export interface PostFXParam{key:string;label:string;type:'number'|'boolean';defaultValue:number|boolean;min?:number;max?:number;step?:number}
export interface PostFXCatalogEntry{type:PostFXType;label:string;category:'light'|'temporal'|'stylize'|'aa'|'screen-space'|'color'|'blur';requires?:string[];cost:'low'|'medium'|'high'|'very-high';params:PostFXParam[];backend:'webgpu'|'webgl2'|'both';fallback:'disable'|PostFXType;quality:{minTier:'low'|'balanced'|'high'|'ultra'};resources:string[]}
type PostFXCatalogInput=Omit<PostFXCatalogEntry,'backend'|'fallback'|'quality'|'resources'>&Partial<Pick<PostFXCatalogEntry,'backend'|'fallback'|'quality'|'resources'>>
const num=(key:string,label:string,defaultValue:number,min:number,max:number,step=.01):PostFXParam=>({key,label,type:'number',defaultValue,min,max,step})
const bool=(key:string,label:string,defaultValue:boolean):PostFXParam=>({key,label,type:'boolean',defaultValue})
const postFXCatalogEntries:PostFXCatalogInput[]=[
 {type:'bloom',label:'Bloom',category:'light',cost:'medium',params:[num('strength','Strength',1,0,5),num('radius','Radius',.25,0,1),num('threshold','Threshold',.8,0,1)]},
 {type:'dof',label:'Depth of Field',category:'screen-space',requires:['depth'],cost:'high',params:[num('focusDistance','Focus Distance',4,.01,50,.01),num('focalLength','Focal Length',.02,.001,.2,.001),num('bokehScale','Bokeh',2,0,10,.05)]},
 {type:'anamorphic',label:'Extended Bloom',category:'light',cost:'high',params:[num('threshold','Threshold',.9,0,1),num('scale','Scale',3,.1,10,.1)]},
 {type:'afterImage',label:'Afterimage',category:'temporal',cost:'medium',params:[num('damp','Damping',.96,0,1,.001)]},
 {type:'chromaticAberration',label:'Chromatic Aberration',category:'stylize',cost:'low',params:[num('strength','Strength',.004,0,.05,.0001)]},
 {type:'dotScreen',label:'Dot Screen',category:'stylize',cost:'low',params:[num('angle','Angle',1.57,0,6.283,.01),num('scale','Scale',1,.1,10,.1)]},
 {type:'film',label:'Film Grain',category:'stylize',cost:'low',params:[num('intensity','Intensity',.12,0,1,.005)]},
 {type:'rgbShift',label:'RGB Shift',category:'stylize',cost:'low',params:[num('amount','Amount',.003,0,.05,.0001),num('angle','Angle',0,0,6.283,.01)]},
 {type:'sobel',label:'Sobel Edge',category:'stylize',cost:'low',params:[]},{type:'sepia',label:'Sepia',category:'color',cost:'low',params:[]},{type:'grayscale',label:'Grayscale',category:'color',cost:'low',params:[]},
 {type:'bleach',label:'Bleach Bypass',category:'color',cost:'low',params:[num('opacity','Opacity',.5,0,1)]},{type:'posterize',label:'Posterize',category:'stylize',cost:'low',params:[num('steps','Steps',8,2,64,1)]},{type:'colorBleeding',label:'Color Bleeding',category:'stylize',cost:'low',params:[num('amount','Amount',.002,0,.01,.0001)]},{type:'scanlines',label:'Scanlines',category:'stylize',cost:'low',params:[num('intensity','Intensity',.3,0,1,.01),num('count','Count',240,20,1200,1),num('speed','Speed',0,-4,4,.01)]},{type:'hue',label:'Hue Rotate',category:'color',cost:'low',params:[num('adjustment','Angle',0,-3.1416,3.1416,.01)]},{type:'saturation',label:'Saturation',category:'color',cost:'low',params:[num('adjustment','Saturation',1,0,4,.01)]},{type:'vignette',label:'Vignette',category:'color',cost:'low',params:[num('intensity','Intensity',.35,0,1),num('smoothness','Smoothness',.55,.01,1)]},
 {type:'gaussianBlur',label:'Gaussian Blur',category:'blur',cost:'high',params:[num('radius','Radius',3,.1,12,.1),num('sigma','Sigma',2,.1,8,.1)]},{type:'hashBlur',label:'Hash Blur',category:'blur',cost:'medium',params:[num('amount','Amount',.08,0,.5,.005),num('repeats','Samples',32,4,96,1)]},{type:'sharpen',label:'Sharpen',category:'color',cost:'medium',params:[num('sharpness','Sharpness',.35,0,2,.01),bool('denoise','Denoise',false)]},{type:'fsr1',label:'FSR1 Sharpen',category:'aa',cost:'medium',params:[num('sharpness','Sharpness',.2,0,2,.01),bool('denoise','Denoise',false)]},
 {type:'boxBlur',label:'Box Blur',category:'blur',cost:'low',params:[num('size','Kernel',1,1,3,1),num('separation','Separation',1,1,12,1),bool('premultipliedAlpha','Premultiplied Alpha',false)]},{type:'denoise',label:'Denoise',category:'screen-space',requires:['depth','normal'],cost:'medium',params:[]},{type:'lensflare',label:'Lens Flare',category:'light',cost:'high',params:[num('threshold','Threshold',.5,0,1,.01),num('ghostSamples','Ghost Samples',4,1,12,1),num('ghostSpacing','Ghost Spacing',.25,.01,1,.01),num('ghostAttenuationFactor','Ghost Attenuation',25,1,100,1),num('downSampleRatio','Downsample',4,1,8,1)]},{type:'outline',label:'Selection Outline',category:'screen-space',cost:'high',params:[num('edgeThickness','Edge Thickness',1,.1,8,.1),num('edgeGlow','Edge Glow',0,0,5,.05),num('downSampleRatio','Downsample',2,1,8,1)]},
 {type:'fxaa',label:'FXAA',category:'aa',cost:'low',params:[]},{type:'smaa',label:'SMAA',category:'aa',cost:'medium',params:[]},{type:'traa',label:'TRAA',category:'aa',requires:['depth','velocity'],cost:'high',params:[]},{type:'taau',label:'TAAU',category:'aa',requires:['depth','velocity'],cost:'high',params:[]},
 {type:'motionBlur',label:'Motion Blur',category:'temporal',requires:['velocity'],cost:'high',params:[num('samples','Samples',16,4,64,1)]},{type:'ssr',label:'Screen Space Reflections',category:'screen-space',requires:['depth','normal'],cost:'very-high',params:[bool('stochastic','Stochastic',true),bool('binaryRefine','Binary Refine',true)]},{type:'ssgi',label:'SSGI',category:'screen-space',requires:['depth','normal'],cost:'very-high',params:[num('giIntensity','GI Intensity',9,0,40,.1),num('aoIntensity','AO Intensity',1,0,2),num('radius','Radius',10,.5,30,.1),num('thickness','Thickness',1,.05,5,.05),num('expFactor','Distribution',2,1,3,.05),num('backfaceLighting','Backface Lighting',0,0,1),bool('temporal','Temporal Filtering',true)]},{type:'gtao',label:'GTAO',category:'screen-space',requires:['depth','normal'],cost:'high',params:[]}
 ,{type:'ssaa',label:'SSAA',category:'aa',cost:'very-high',backend:'webgpu',fallback:'fxaa',quality:{minTier:'high'},params:[]}
 ,{type:'sss',label:'Subsurface Scattering',category:'screen-space',requires:['depth','scene.mainLight'],resources:['scene.mainLight'],cost:'very-high',backend:'webgpu',fallback:'disable',quality:{minTier:'high'},params:[]}
 ,{type:'godrays',label:'God Rays',category:'light',requires:['depth','scene.godraysLight'],resources:['scene.godraysLight'],cost:'high',backend:'webgpu',fallback:'disable',quality:{minTier:'balanced'},params:[]}
 ,{type:'lut3d',label:'3D LUT',category:'color',requires:['postfx.lut3d'],resources:['postfx.lut3d'],cost:'medium',backend:'webgpu',fallback:'disable',quality:{minTier:'balanced'},params:[num('intensity','Intensity',1,0,1)]}
 ,{type:'transition',label:'Transition',category:'temporal',requires:['postfx.transition'],resources:['postfx.transition'],cost:'medium',backend:'webgpu',fallback:'disable',quality:{minTier:'balanced'},params:[num('mix','Mix',0,0,1)]}
 ,{type:'pixelation',label:'Pixelation',category:'stylize',cost:'low',backend:'webgpu',fallback:'disable',quality:{minTier:'low'},params:[num('pixelSize','Pixel Size',6,1,32,1),num('normalEdge','Normal Edge',.3,0,2),num('depthEdge','Depth Edge',.4,0,2)]}
 ,{type:'retro',label:'Retro Pass',category:'stylize',cost:'medium',backend:'webgpu',fallback:'disable',quality:{minTier:'balanced'},params:[]}
 ,{type:'radialBlur',label:'Radial Blur',category:'blur',cost:'medium',backend:'webgpu',fallback:'disable',quality:{minTier:'balanced'},params:[num('strength','Strength',.2,0,1)]}
 ,{type:'bilateralBlur',label:'Bilateral Blur',category:'blur',cost:'high',backend:'webgpu',fallback:'gaussianBlur',quality:{minTier:'high'},params:[num('sigma','Sigma',2,.1,8),num('sigmaColor','Sigma Color',.1,.01,1)]}
 ,{type:'recurrentDenoise',label:'Recurrent Denoise',category:'temporal',requires:['depth','normal'],cost:'very-high',backend:'webgpu',fallback:'denoise',quality:{minTier:'high'},params:[]}
]
export const postFXCatalog:PostFXCatalogEntry[]=postFXCatalogEntries.map(entry=>({backend:'both',fallback:'disable',quality:{minTier:'low'},resources:[],...entry}))
/**
 * Default chain position. Catalog order, except anti-aliasing / temporal resolve, which must see the
 * finished image: TRAA before SSGI would leave the GI noise unresolved.
 */
export const defaultPostFXOrder=(type:PostFXType)=>{const index=postFXCatalog.findIndex(entry=>entry.type===type);return postFXCatalog[index]?.category==='aa'?4500+index:(index+1)*100}
export const postFXPresets={clean:[{type:'fxaa',enabled:true,order:900,params:{}}],cinematic:[{type:'bloom',enabled:true,order:100,params:{strength:.65,radius:.25,threshold:.82}},{type:'dof',enabled:true,order:200,params:{focusDistance:4,focalLength:.018,bokehScale:1.4}},{type:'vignette',enabled:true,order:700,params:{intensity:.22,smoothness:.65}},{type:'film',enabled:true,order:800,params:{intensity:.035}},{type:'traa',enabled:true,order:900,params:{}}],dream:[{type:'bloom',enabled:true,order:100,params:{strength:1.4,radius:.6,threshold:.55}},{type:'chromaticAberration',enabled:true,order:300,params:{strength:.002}},{type:'vignette',enabled:true,order:800,params:{intensity:.18,smoothness:.7}}],analog:[{type:'bleach',enabled:true,order:200,params:{opacity:.15}},{type:'film',enabled:true,order:400,params:{intensity:.12}},{type:'vignette',enabled:true,order:500,params:{intensity:.4,smoothness:.5}},{type:'fxaa',enabled:true,order:900,params:{}}],performance:[{type:'fxaa',enabled:true,order:900,params:{}}]} as const
