import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { useMemo, useRef } from 'react'
import { Box3, MathUtils, Vector3 } from 'three'
import { cameraPresets, resolveCameraGoal, type CameraGoal, type CameraPreset } from './scene-math'
export { cameraPresets, resolveCameraGoal, type CameraGoal, type CameraPreset, type CameraPresetDefinition } from './scene-math'
export interface CameraProps{mode?:'perspective'|'orthographic';preset?:CameraPreset;position?:[number,number,number];target?:[number,number,number];fov?:number;lens?:number;filmGauge?:number;zoom?:number;near?:number;far?:number;makeDefault?:boolean;lookAt?:boolean;fit?:boolean;fitMargin?:number;transition?:number;updateRate?:number}
const lensToFov=(lens:number,film=36)=>2*Math.atan(film/(2*lens))*180/Math.PI
export function Camera({mode='perspective',preset='product',position,target,fov,lens,filmGauge=36,zoom=80,near,far,makeDefault=true,lookAt=true,fit=false,fitMargin=1.25,transition=8,updateRate=4}:CameraProps){const p=cameraPresets[preset],scene=useThree(s=>s.scene),viewport=useThree(s=>s.size),ref=useRef<any>(null),elapsed=useRef(0),goal=useRef<CameraGoal>(resolveCameraGoal(preset,null,viewport,{position,target,fov,zoom})),resolvedFov=lens?lensToFov(lens,filmGauge):fov??p.fov;useFrame((_state,delta)=>{elapsed.current+=delta;if(fit&&elapsed.current>=1/Math.max(1,updateRate)){elapsed.current=0;const bounds=measureCameraBounds(scene);goal.current=resolveCameraGoal(preset,bounds,viewport,{position,target,fov:resolvedFov,zoom});if(bounds){const center=bounds.getCenter(new Vector3()),size=bounds.getSize(new Vector3());goal.current.position.copy(center).add(goal.current.position.clone().sub(center).multiplyScalar(fitMargin));goal.current.target.copy(center);goal.current.zoom=Math.max(1,zoom/Math.max(1,size.length()*.45));}}else if(!fit)goal.current=resolveCameraGoal(preset,null,viewport,{position,target,fov:resolvedFov,zoom});if(ref.current){const alpha=transition<=0?1:1-Math.exp(-transition*delta);ref.current.position.lerp(goal.current.position,alpha);if(mode==='perspective')ref.current.fov=MathUtils.lerp(ref.current.fov,goal.current.fov,alpha);else ref.current.zoom=MathUtils.lerp(ref.current.zoom,goal.current.zoom,alpha);ref.current.updateProjectionMatrix?.();if(lookAt)ref.current.lookAt(goal.current.target);}});return mode==='orthographic'?<OrthographicCamera ref={ref} makeDefault={makeDefault} position={position??p.position} zoom={zoom} near={near??p.near} far={far??p.far}/>:<PerspectiveCamera ref={ref} makeDefault={makeDefault} position={position??p.position} fov={resolvedFov} near={near??p.near} far={far??p.far}/>}
function measureCameraBounds(scene:import('three').Object3D){const bounds=new Box3(),hidden:import('three').Object3D[]=[];scene.traverse(object=>{if(object.name.startsWith('artinos-')){if(object.visible){hidden.push(object);object.visible=false}}});bounds.setFromObject(scene,true);hidden.forEach(object=>{object.visible=true});return bounds.isEmpty()?null:bounds}
export function CameraTarget({target=[0,0,0],damping=0}:{target?:[number,number,number];damping?:number}){const camera=useThree(s=>s.camera);const desired=useMemo(()=>new Vector3(...target),[target]);useFrame((_s,delta)=>{if(damping>0){const current=camera.getWorldDirection(new Vector3()).add(camera.position);current.lerp(desired,1-Math.exp(-damping*delta));camera.lookAt(current)}else camera.lookAt(desired)});return null}
