import { Box3, MathUtils, Vector3, type Object3D } from 'three'

export type CameraPreset='front'|'back'|'top'|'bottom'|'left'|'right'|'isometric'|'product'|'portrait'|'wide'|'cinematic'|'macro'
export interface CameraPresetDefinition{position:[number,number,number];target:[number,number,number];fov:number;near:number;far:number}
export const cameraPresets:Record<CameraPreset,CameraPresetDefinition>={
 front:{position:[0,0,5],target:[0,0,0],fov:45,near:.01,far:1000},back:{position:[0,0,-5],target:[0,0,0],fov:45,near:.01,far:1000},top:{position:[0,7,.001],target:[0,0,0],fov:45,near:.01,far:1000},bottom:{position:[0,-7,.001],target:[0,0,0],fov:45,near:.01,far:1000},left:{position:[-6,0,0],target:[0,0,0],fov:45,near:.01,far:1000},right:{position:[6,0,0],target:[0,0,0],fov:45,near:.01,far:1000},isometric:{position:[4,3,4],target:[0,0,0],fov:42,near:.01,far:1000},product:{position:[0,1.4,5.5],target:[0,.2,0],fov:45,near:.01,far:1000},portrait:{position:[0,1.6,4.3],target:[0,.7,0],fov:38,near:.01,far:1000},wide:{position:[0,2,8],target:[0,.2,0],fov:58,near:.01,far:1500},cinematic:{position:[3,1.6,6],target:[0,.5,0],fov:34,near:.01,far:1200},macro:{position:[0,.5,2.3],target:[0,.25,0],fov:28,near:.001,far:250}
}
export interface CameraGoal{position:Vector3;target:Vector3;fov:number;zoom:number}
export interface CameraGoalOptions{position?:[number,number,number];target?:[number,number,number];fov?:number;zoom?:number}
export const resolveCameraGoal=(preset:CameraPreset,bounds:Box3|null,viewport:{width:number;height:number},props:CameraGoalOptions={}):CameraGoal=>{const definition=cameraPresets[preset];if(!bounds)return{position:new Vector3(...(props.position??definition.position)),target:new Vector3(...(props.target??definition.target)),fov:props.fov??definition.fov,zoom:props.zoom??80};const center=bounds.getCenter(new Vector3()),size=bounds.getSize(new Vector3()),aspect=viewport.width/Math.max(1,viewport.height),distance=Math.max(size.length()*1.25,size.y/Math.max(.2,Math.tan(MathUtils.degToRad(props.fov??definition.fov)*.5))/Math.max(.7,aspect)),direction=new Vector3(...definition.position).sub(new Vector3(...definition.target)).normalize();return{position:props.position?new Vector3(...props.position):center.clone().add(direction.multiplyScalar(distance)),target:props.target?new Vector3(...props.target):center,fov:props.fov??definition.fov,zoom:props.zoom??80}}

export const measureContentBounds=(scene:Object3D,exclusions=['artinos-environment','artinos-ground-grid','artinos-shadows'])=>{const candidate=new Box3(),hidden=new Map<Object3D,boolean>();scene.traverse(object=>{if(exclusions.some(name=>object.name.startsWith(name))){hidden.set(object,object.visible);object.visible=false}});candidate.setFromObject(scene,true);for(const[object,visible]of hidden)object.visible=visible;return candidate.isEmpty()?null:candidate}
export const resolveAdaptiveRoom=(bounds:Box3|null,viewport:{width:number;height:number},groundY:number,margin=1.35)=>{const size=bounds?.getSize(new Vector3())??new Vector3(4,3,4),center=bounds?.getCenter(new Vector3())??new Vector3(),aspect=viewport.width/Math.max(1,viewport.height),scale:[number,number,number]=[Math.max(6,size.x*margin,4*aspect),Math.max(4,size.y*margin),Math.max(6,size.z*margin)];return{scale,position:[center.x,groundY-.05,center.z-scale[2]*.3] as [number,number,number]}}
export const resolveDprRange=(range:[number,number],scalar:number)=>Math.max(range[0],Math.min(range[1],range[1]*scalar))
