import { useEffect, useMemo } from 'react'
import { CanvasTexture, LinearFilter } from 'three/webgpu'

export type ShadowPreset='off'|'hard'|'soft'|'contact'|'studio'|'cinematic'
export interface ShadowsProps{preset?:ShadowPreset;opacity?:number;blur?:number;size?:number;y?:number;samples?:number;focus?:number;far?:number;color?:string}
const presets:Record<Exclude<ShadowPreset,'off'>,{opacity:number;blur:number}>={hard:{opacity:.72,blur:.12},soft:{opacity:.52,blur:.5},contact:{opacity:.62,blur:.35},studio:{opacity:.46,blur:.62},cinematic:{opacity:.56,blur:.78}}

/** WebGPU-safe fallback while Drei alpha's WebGPU barrel imports removed WebGLCubeRenderTarget. */
export function Shadows({preset='studio',opacity,blur,size=10,y=-1.13,samples=32,focus=0,far=12,color='#000000'}:ShadowsProps){if(preset==='off')return null;const selected=presets[preset],softness=Math.max(.04,Math.min(.94,blur??selected.blur)),resolution=Math.max(64,Math.min(512,2**Math.ceil(Math.log2(Math.max(4,samples)*8)))),texture=useMemo(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=resolution;const context=canvas.getContext('2d');if(!context)return null;const center=resolution/2,gradient=context.createRadialGradient(center,center,Math.max(0,center*(.08+focus*.18)),center,center,center);gradient.addColorStop(0,color);gradient.addColorStop(Math.max(.02,1-softness),color);gradient.addColorStop(1,'transparent');context.fillStyle=gradient;context.fillRect(0,0,resolution,resolution);const next=new CanvasTexture(canvas);next.minFilter=next.magFilter=LinearFilter;next.needsUpdate=true;return next},[color,focus,resolution,softness]);useEffect(()=>()=>texture?.dispose(),[texture]);if(!texture)return null;const spread=size*Math.max(.35,Math.min(2,far/12));return <mesh position={[0,y,0]} rotation-x={-Math.PI/2} scale={[spread,spread,1]} renderOrder={-1}><planeGeometry/><meshBasicMaterial map={texture} transparent opacity={opacity??selected.opacity} depthWrite={false} toneMapped={false}/></mesh>}
