import type { RoomParams, SimOpts } from '../room-params';
import type { LightParams, StagingParams } from '../lighting';

/**
 * Preset = a complete scene recipe: environment + theme + parameter overrides
 * + simulation options (+ optional quality tier). Built-in presets are grouped
 * into curated collections ("templates"); user presets are stored alongside
 * and share the same shape.
 */
export interface Preset {
  id: string;
  label: string;
  blurb?: string;
  envId: string;
  themeId: string;
  /** space architecture id (defaults to 'cyclo') */
  spaceId?: string;
  params?: Partial<RoomParams>;
  sim?: Partial<SimOpts>;
  light?: Partial<LightParams>;
  staging?: Partial<StagingParams>;
  quality?: string;
  builtin?: boolean;
}

export interface PresetCollection {
  id: string;
  label: string;
  blurb: string;
  presets: Preset[];
}

const B = (p: Omit<Preset, 'builtin'>): Preset => ({ ...p, builtin: true });

export const COLLECTIONS: PresetCollection[] = [
  {
    id: 'signature',
    label: 'Signature',
    blurb: 'Reference compositions — the room at its most architectural.',
    presets: [
      B({
        id: 'atelier',
        label: 'Atelier',
        blurb: 'Warm daylight studio with the matte still-life.',
        envId: 'sculpture',
        themeId: 'studio',
        params: { fov: 35, margin: 0.06, ssgiIntensity: 1.0, exposure: 1.05 },
      }),
      B({
        id: 'golden-hall',
        label: 'Golden Hall',
        blurb: 'Limestone chamber, floating stage, honeyed key light.',
        envId: 'stage',
        themeId: 'limestone',
        params: { lightIntensity: 1.15, exposure: 1.12, radius: 1.1, fov: 33 },
      }),
      B({
        id: 'noir-orbit',
        label: 'Noir Orbit',
        blurb: 'Charcoal shell, amber key, orbital mobile. SSGI showcase.',
        envId: 'kinetic',
        themeId: 'noir',
        params: { ssgiIntensity: 1.5, lightIntensity: 1.5, exposure: 1.15, roughness: 0.85 },
        sim: { speed: 0.8 },
      }),
      B({
        id: 'clay-vault',
        label: 'Clay Vault',
        blurb: 'Terracotta walls with deep coves and a taller vault.',
        envId: 'sculpture',
        themeId: 'terracotta',
        params: { height: 5.8, radius: 1.5, rearInset: 0.8, exposure: 1.1 },
      }),
    ],
  },
  {
    id: 'kinetic',
    label: 'Kinetic',
    blurb: 'Motion pieces driven by the adaptive bounds.',
    presets: [
      B({
        id: 'metronome',
        label: 'Metronome',
        blurb: 'Concrete pendulum wave — count adapts to the room width.',
        envId: 'wave',
        themeId: 'concrete',
        params: { ssgiIntensity: 1.1, lightIntensity: 1.15, fov: 37 },
        sim: { speed: 1, density: 1 },
      }),
      B({
        id: 'orrery',
        label: 'Orrery',
        blurb: 'Slow precessing rings in a sage museum room.',
        envId: 'kinetic',
        themeId: 'sage',
        params: { depth: 8, fov: 32, exposure: 1.0 },
        sim: { speed: 0.6 },
      }),
      B({
        id: 'rush',
        label: 'Rush',
        blurb: 'Double-speed pendulum storm in noir.',
        envId: 'wave',
        themeId: 'noir',
        params: { lightIntensity: 1.6, ssgiIntensity: 1.3 },
        sim: { speed: 1.9, density: 1.4 },
      }),
    ],
  },
  {
    id: 'playful',
    label: 'Playful',
    blurb: 'Physics inside environment.bounds — click to stir.',
    presets: [
      B({
        id: 'ball-pit',
        label: 'Ball Pit',
        blurb: 'Dense terracotta ball pool. The SSGI classic.',
        envId: 'pool',
        themeId: 'terracotta',
        params: { ssgiIntensity: 1.2, exposure: 1.1 },
        sim: { density: 1.6 },
      }),
      B({
        id: 'antigravity',
        label: 'Antigravity',
        blurb: 'Weightless drift through a concrete shell.',
        envId: 'drift',
        themeId: 'concrete',
        params: { depth: 8, lightIntensity: 1.2 },
        sim: { density: 1.2, speed: 1.1 },
      }),
      B({
        id: 'porcelain-rain',
        label: 'Porcelain Rain',
        blurb: 'Sparse pale spheres settling in the studio.',
        envId: 'pool',
        themeId: 'studio',
        params: { ssgiIntensity: 0.9, exposure: 1.0 },
        sim: { density: 0.55 },
      }),
    ],
  },
  {
    id: 'architecture',
    label: 'Architecture',
    blurb: 'Space types — the same adaptive logic wearing different shells.',
    presets: [
      B({
        id: 'exhibit-bay',
        label: 'Exhibit Bay',
        blurb: 'Gallery niche + limestone: curated masterpiece staging.',
        envId: 'sculpture',
        themeId: 'limestone',
        spaceId: 'niche',
        params: { fov: 33, margin: 0.05, exposure: 1.08 },
      }),
      B({
        id: 'lightworks',
        label: 'Lightworks',
        blurb: 'Lightbox panels + weightless drift. Bounce study.',
        envId: 'drift',
        themeId: 'concrete',
        spaceId: 'lightbox',
        params: { ssgiIntensity: 1.3, lightIntensity: 0.7, roughness: 0.85 },
        sim: { density: 1, speed: 0.9 },
      }),
      B({
        id: 'portal',
        label: 'Portal',
        blurb: 'Noir monolith frame around the still-life. Poster shot.',
        envId: 'sculpture',
        themeId: 'noir',
        spaceId: 'monolith',
        params: { depth: 7, fov: 33, lightIntensity: 1.5, ssgiIntensity: 1.4, exposure: 1.15 },
      }),
      B({
        id: 'procession',
        label: 'Procession',
        blurb: 'Runway corridor + pendulum wave marching into depth.',
        envId: 'wave',
        themeId: 'concrete',
        spaceId: 'runway',
        params: { depth: 11, rearInset: 0.6, fov: 38, radius: 0.7 },
        sim: { speed: 0.9 },
      }),
      B({
        id: 'loft-light',
        label: 'Loft Light',
        blurb: 'Interior slice: window band, bench, warm natural key.',
        envId: 'sculpture',
        themeId: 'studio',
        spaceId: 'slice',
        params: { lightIntensity: 0.75, exposure: 1.12 },
      }),
      B({
        id: 'terrace',
        label: 'Terrace',
        blurb: 'Sage tier deck under the orbital mobile.',
        envId: 'kinetic',
        themeId: 'sage',
        spaceId: 'tiers',
        params: { depth: 7.5 },
        sim: { speed: 0.7 },
      }),
      B({
        id: 'solarium',
        label: 'Solarium',
        blurb: 'Open pavilion skylight over the terracotta still-life.',
        envId: 'sculpture',
        themeId: 'terracotta',
        spaceId: 'pavilion',
        params: { height: 6, lightIntensity: 0.85, exposure: 1.1 },
      }),
      B({
        id: 'haze',
        label: 'Haze',
        blurb: 'Atmos volume: fog, glow field, one downlight, slow rings.',
        envId: 'kinetic',
        themeId: 'noir',
        spaceId: 'atmos',
        params: { depth: 9, lightIntensity: 0.55, ssgiIntensity: 1.4, exposure: 1.15 },
        sim: { speed: 0.5 },
      }),
    ],
  },
  {
    id: 'photography',
    label: 'Photography',
    blurb: 'Studio-grade lighting setups — product, beauty, fashion, editorial.',
    presets: [
      B({
        id: 'infinity-white',
        label: 'Infinity White',
        blurb: 'Pure white cyclorama — classic product infinity wall.',
        envId: 'sculpture',
        themeId: 'pure-white',
        spaceId: 'cyclo',
        params: {
          radius: 2.2,
          rearInset: 0,
          roughness: 0.98,
          lightIntensity: 1.4,
          fillIntensity: 1.3,
          ssgiIntensity: 0.9,
          exposure: 1.15,
          fov: 36,
          margin: 0.04,
          keyAzimuth: -20,
        },
        quality: 'high',
      }),
      B({
        id: 'paper-sweep',
        label: 'Paper Sweep',
        blurb: 'Warm paper cyclorama with soft key — catalog still-life.',
        envId: 'sculpture',
        themeId: 'paper-white',
        spaceId: 'cyclo',
        params: {
          radius: 1.8,
          rearInset: 0.1,
          lightIntensity: 1.2,
          fillIntensity: 1.1,
          exposure: 1.08,
          fov: 34,
          keyAzimuth: -32,
        },
      }),
      B({
        id: 'daylight-pack',
        label: 'Daylight Packshot',
        blurb: '5600K neutral packshot — clean, color-accurate product.',
        envId: 'sculpture',
        themeId: 'daylight',
        spaceId: 'cyclo',
        params: {
          radius: 1.4,
          lightIntensity: 1.3,
          fillIntensity: 1.4,
          ssgiIntensity: 0.85,
          exposure: 1.1,
          fov: 35,
          keyAzimuth: -25,
          margin: 0.05,
        },
        quality: 'high',
      }),
      B({
        id: 'tungsten-glow',
        label: 'Tungsten Glow',
        blurb: '3200K warm tungsten — evening product mood.',
        envId: 'sculpture',
        themeId: 'tungsten',
        spaceId: 'cyclo',
        params: {
          lightIntensity: 1.35,
          fillIntensity: 0.7,
          ssgiIntensity: 1.2,
          exposure: 1.12,
          keyAzimuth: -40,
          radius: 1.2,
        },
      }),
      B({
        id: 'softbox-beauty',
        label: 'Softbox Beauty',
        blurb: 'Ultra-soft diffused beauty light — cosmetics & glass.',
        envId: 'sculpture',
        themeId: 'softbox',
        spaceId: 'lightbox',
        params: {
          lightIntensity: 0.6,
          fillIntensity: 1.6,
          ssgiIntensity: 1.5,
          exposure: 1.05,
          roughness: 0.99,
          fov: 32,
          margin: 0.06,
        },
        quality: 'high',
      }),
      B({
        id: 'high-key-hero',
        label: 'High Key Hero',
        blurb: 'Blown-out bright key — fashion / lifestyle hero shot.',
        envId: 'sculpture',
        themeId: 'high-key',
        spaceId: 'cyclo',
        params: {
          lightIntensity: 2.0,
          fillIntensity: 1.8,
          ssgiIntensity: 0.6,
          exposure: 1.35,
          radius: 1.6,
          fov: 38,
          keyAzimuth: 0,
        },
      }),
      B({
        id: 'low-key-drama',
        label: 'Low Key Drama',
        blurb: 'Chiaroscuro still-life — one hard key, deep shadows.',
        envId: 'sculpture',
        themeId: 'low-key',
        spaceId: 'cyclo',
        params: {
          lightIntensity: 1.8,
          fillIntensity: 0.15,
          ssgiIntensity: 1.6,
          exposure: 1.2,
          keyAzimuth: -55,
          radius: 0.9,
          fov: 30,
          margin: 0.08,
        },
        quality: 'high',
      }),
      B({
        id: 'chrome-reflect',
        label: 'Chrome Reflect',
        blurb: 'Polished shell + lightbox — metal / glass / caustic study.',
        envId: 'sculpture',
        themeId: 'chrome-lab',
        spaceId: 'lightbox',
        params: {
          roughness: 0.4,
          lightIntensity: 0.55,
          fillIntensity: 1.2,
          ssgiIntensity: 1.8,
          exposure: 1.1,
          bumpScale: 0.15,
          fov: 33,
        },
        quality: 'high',
      }),
      B({
        id: 'fashion-gray-set',
        label: 'Fashion Gray',
        blurb: 'Mid-gray seamless — classic fashion studio backdrop.',
        envId: 'sculpture',
        themeId: 'fashion-gray',
        spaceId: 'cyclo',
        params: {
          radius: 1.8,
          rearInset: 0,
          lightIntensity: 1.3,
          fillIntensity: 1.0,
          keyAzimuth: -30,
          exposure: 1.1,
          fov: 36,
        },
      }),
      B({
        id: 'beauty-flush',
        label: 'Beauty Flush',
        blurb: 'Warm blush beauty shell — soft skin tones, cosmetics.',
        envId: 'sculpture',
        themeId: 'beauty-blush',
        spaceId: 'lightbox',
        params: {
          lightIntensity: 0.7,
          fillIntensity: 1.5,
          ssgiIntensity: 1.3,
          exposure: 1.08,
          keyAzimuth: -15,
          fov: 32,
          radius: 1.3,
        },
      }),
      B({
        id: 'product-slate-set',
        label: 'Product Slate',
        blurb: 'Cool slate packshot stage — tech / electronics hero.',
        envId: 'stage',
        themeId: 'product-slate',
        spaceId: 'cyclo',
        params: {
          lightIntensity: 1.35,
          fillIntensity: 1.2,
          ssgiIntensity: 1.0,
          exposure: 1.1,
          keyAzimuth: -28,
          fov: 34,
          margin: 0.05,
        },
        quality: 'high',
      }),
      B({
        id: 'sepia-still',
        label: 'Sepia Still',
        blurb: 'Warm sepia print look — archival still-life mood.',
        envId: 'sculpture',
        themeId: 'sepia-print',
        spaceId: 'niche',
        params: {
          lightIntensity: 1.2,
          fillIntensity: 0.8,
          ssgiIntensity: 1.15,
          exposure: 1.05,
          keyAzimuth: -35,
          fov: 32,
          radius: 1.0,
        },
      }),
    ],
  },
  {
    id: 'studio-sets',
    label: 'Studio Sets',
    blurb: 'Full studio configurations — cyc walls, stages, lighting bays.',
    presets: [
      B({
        id: 'cyc-wall-xl',
        label: 'Cyc Wall XL',
        blurb: 'Maximum cove cyclorama — full-body / large-product infinity.',
        envId: 'void',
        themeId: 'pure-white',
        spaceId: 'cyclo',
        params: {
          height: 7,
          depth: 10,
          radius: 3.2,
          rearInset: 0,
          roughness: 0.98,
          lightIntensity: 1.5,
          fillIntensity: 1.4,
          ssgiIntensity: 0.8,
          exposure: 1.2,
          fov: 40,
          margin: 0.03,
          keyAzimuth: -18,
        },
        quality: 'high',
      }),
      B({
        id: 'tabletop-pack',
        label: 'Tabletop Pack',
        blurb: 'Tight tabletop product bay — jewelry, watches, small goods.',
        envId: 'sculpture',
        themeId: 'daylight',
        spaceId: 'cyclo',
        params: {
          height: 3.2,
          depth: 4,
          radius: 0.9,
          lightIntensity: 1.4,
          fillIntensity: 1.5,
          ssgiIntensity: 0.9,
          exposure: 1.12,
          fov: 42,
          subjectScale: 1.4,
          margin: 0.06,
          keyAzimuth: -22,
        },
        quality: 'high',
      }),
      B({
        id: 'beauty-bay',
        label: 'Beauty Bay',
        blurb: 'Lightbox beauty bay — dual soft panels, blush shell.',
        envId: 'sculpture',
        themeId: 'beauty-blush',
        spaceId: 'lightbox',
        params: {
          height: 4.2,
          depth: 5,
          radius: 1.1,
          lightIntensity: 0.55,
          fillIntensity: 1.7,
          ssgiIntensity: 1.6,
          exposure: 1.08,
          fov: 30,
          keyAzimuth: 0,
          margin: 0.07,
        },
        quality: 'high',
      }),
      B({
        id: 'editorial-loft',
        label: 'Editorial Loft',
        blurb: 'Window-lit loft slice — lifestyle product storytelling.',
        envId: 'sculpture',
        themeId: 'paper-white',
        spaceId: 'slice',
        params: {
          height: 5.5,
          depth: 7,
          lightIntensity: 0.7,
          fillIntensity: 0.9,
          ssgiIntensity: 1.2,
          exposure: 1.15,
          keyAzimuth: -50,
          fov: 34,
        },
      }),
      B({
        id: 'runway-show',
        label: 'Runway Show',
        blurb: 'Fashion corridor with strip lights — reveal sequence.',
        envId: 'void',
        themeId: 'fashion-gray',
        spaceId: 'runway',
        params: {
          depth: 14,
          height: 5.5,
          radius: 0.6,
          rearInset: 0.8,
          lightIntensity: 1.2,
          fillIntensity: 0.6,
          ssgiIntensity: 1.1,
          exposure: 1.1,
          fov: 40,
          keyAzimuth: 0,
        },
      }),
      B({
        id: 'gallery-white',
        label: 'Gallery White',
        blurb: 'Museum white niche — collectible / art object pedestal.',
        envId: 'sculpture',
        themeId: 'pure-white',
        spaceId: 'niche',
        params: {
          radius: 0.85,
          rearInset: 0.1,
          lightIntensity: 1.3,
          fillIntensity: 1.2,
          ssgiIntensity: 1.0,
          exposure: 1.1,
          fov: 32,
          margin: 0.05,
          keyAzimuth: -25,
        },
        quality: 'high',
      }),
      B({
        id: 'metal-lab',
        label: 'Metal Lab',
        blurb: 'Chrome lightbox lab — automotive / tech surface study.',
        envId: 'stage',
        themeId: 'chrome-lab',
        spaceId: 'lightbox',
        params: {
          roughness: 0.35,
          bumpScale: 0.1,
          lightIntensity: 0.5,
          fillIntensity: 1.3,
          ssgiIntensity: 2.0,
          exposure: 1.15,
          fov: 33,
          depth: 6.5,
        },
        quality: 'ultra',
      }),
      B({
        id: 'noir-portrait',
        label: 'Noir Portrait',
        blurb: 'Low-key portrait chamber — Rembrandt-style side key.',
        envId: 'sculpture',
        themeId: 'low-key',
        spaceId: 'cyclo',
        params: {
          lightIntensity: 1.7,
          fillIntensity: 0.1,
          ssgiIntensity: 1.5,
          exposure: 1.18,
          keyAzimuth: -62,
          radius: 1.0,
          fov: 28,
          margin: 0.1,
          targetBias: 0.12,
        },
        quality: 'high',
      }),
      B({
        id: 'tungsten-set',
        label: 'Tungsten Set',
        blurb: 'Warm tungsten studio — evening editorial / lifestyle.',
        envId: 'sculpture',
        themeId: 'tungsten',
        spaceId: 'slice',
        params: {
          lightIntensity: 0.8,
          fillIntensity: 0.6,
          ssgiIntensity: 1.3,
          exposure: 1.1,
          keyAzimuth: -45,
          fov: 33,
          depth: 7,
        },
      }),
      B({
        id: 'softbox-float',
        label: 'Softbox Float',
        blurb: 'Floating stage in a softbox bay — elevated product hero.',
        envId: 'stage',
        themeId: 'softbox',
        spaceId: 'lightbox',
        params: {
          lightIntensity: 0.55,
          fillIntensity: 1.5,
          ssgiIntensity: 1.4,
          exposure: 1.05,
          fov: 34,
          radius: 1.2,
          keyAzimuth: -10,
        },
        quality: 'high',
      }),
      B({
        id: 'atmos-product',
        label: 'Atmos Product',
        blurb: 'Haze volume product shot — cinematic depth, one key.',
        envId: 'sculpture',
        themeId: 'product-slate',
        spaceId: 'atmos',
        params: {
          depth: 9,
          lightIntensity: 0.5,
          fillIntensity: 0.4,
          ssgiIntensity: 1.5,
          exposure: 1.2,
          keyAzimuth: -30,
          fov: 35,
        },
        quality: 'high',
      }),
      B({
        id: 'tier-display',
        label: 'Tier Display',
        blurb: 'Retail tier deck + pure white — multi-product lineup.',
        envId: 'void',
        themeId: 'pure-white',
        spaceId: 'tiers',
        params: {
          depth: 8,
          lightIntensity: 1.4,
          fillIntensity: 1.3,
          ssgiIntensity: 0.9,
          exposure: 1.12,
          fov: 36,
          keyAzimuth: -22,
          radius: 1.2,
        },
        quality: 'high',
      }),
    ],
  },
  {
    id: 'lighting',
    label: 'Lighting',
    blurb: 'Studio light modes + staging setups for product and editorial.',
    presets: [
      B({
        id: 'lit-three-point',
        label: 'Three-Point',
        blurb: 'Classic studio key + fill + rim on pure white cyc.',
        envId: 'sculpture',
        themeId: 'pure-white',
        spaceId: 'cyclo',
        light: {
          mode: 'studio',
          master: 1,
          keyIntensity: 2.6,
          keyAzimuth: -28,
          keyElevation: 42,
          fillIntensity: 0.55,
          rimIntensity: 0.8,
          rimAzimuth: 155,
          ambient: 0.4,
        },
        staging: { shadowCatcher: true, shadowCatcherOpacity: 0.25, plinth: false },
        quality: 'high',
      }),
      B({
        id: 'lit-softbox-beauty',
        label: 'Softbox Beauty',
        blurb: 'Twin rect-area panels + top fill. Cosmetics grade.',
        envId: 'sculpture',
        themeId: 'beauty-blush',
        spaceId: 'lightbox',
        light: {
          mode: 'softbox',
          master: 1.05,
          keyIntensity: 0.5,
          softboxIntensity: 2.6,
          softboxSize: 1.4,
          topIntensity: 0.9,
          fillIntensity: 0.3,
          ambient: 0.35,
          shadowSoftness: 0.85,
        },
        staging: { plinth: true, plinthHeight: 0.35, plinthRadius: 0.55, shadowCatcher: true },
        quality: 'high',
      }),
      B({
        id: 'lit-dramatic-noir',
        label: 'Dramatic Noir',
        blurb: 'Hard side key, deep fill cut, strong rim kicker.',
        envId: 'sculpture',
        themeId: 'low-key',
        spaceId: 'cyclo',
        light: {
          mode: 'dramatic',
          master: 1.1,
          keyIntensity: 3.5,
          keyAzimuth: -58,
          keyElevation: 26,
          keySoftness: 0.1,
          fillIntensity: 0.06,
          rimIntensity: 1.8,
          rimAzimuth: 148,
          ambient: 0.15,
          shadowSoftness: 0.12,
        },
        staging: { backdrop: true, backdropOffset: 1.4, shadowCatcher: true, floorSheen: 0.15 },
        quality: 'high',
      }),
      B({
        id: 'lit-product-pack',
        label: 'Product Packshot',
        blurb: 'Top key + softbox sides + turntable. Catalog ready.',
        envId: 'sculpture',
        themeId: 'daylight',
        spaceId: 'cyclo',
        light: {
          mode: 'product',
          master: 1.1,
          keyIntensity: 1.5,
          keyElevation: 72,
          topIntensity: 1.8,
          softboxIntensity: 2.0,
          softboxSize: 1.1,
          rimIntensity: 0.35,
          ambient: 0.4,
        },
        staging: {
          plinth: true,
          plinthHeight: 0.28,
          plinthRadius: 0.65,
          turntable: true,
          turntableSpeed: 3.5,
          shadowCatcher: true,
        },
        quality: 'high',
      }),
      B({
        id: 'lit-gallery-spot',
        label: 'Gallery Spot',
        blurb: 'Museum overhead + soft ambient. Exhibit pedestal.',
        envId: 'sculpture',
        themeId: 'pure-white',
        spaceId: 'niche',
        light: {
          mode: 'gallery',
          master: 1,
          topIntensity: 2.4,
          keyIntensity: 1.1,
          fillIntensity: 0.5,
          ambient: 0.55,
          accentIntensity: 0.4,
        },
        staging: { plinth: true, plinthHeight: 0.5, plinthRadius: 0.6, shadowCatcher: true },
        quality: 'high',
      }),
      B({
        id: 'lit-daylight-loft',
        label: 'Daylight Loft',
        blurb: 'Cool window softbox + warm sun key through the slice.',
        envId: 'sculpture',
        themeId: 'paper-white',
        spaceId: 'slice',
        light: {
          mode: 'daylight',
          master: 1.05,
          keyIntensity: 2.6,
          keyAzimuth: -48,
          keyElevation: 34,
          softboxIntensity: 2.2,
          softboxSize: 1.5,
          softboxColor: '#e8f0ff',
          fillIntensity: 0.65,
          ambient: 0.48,
        },
        staging: { shadowCatcher: true, floorSheen: 0.2 },
      }),
      B({
        id: 'lit-neon-editorial',
        label: 'Neon Editorial',
        blurb: 'Colored practicals + hard key. Night fashion mood.',
        envId: 'sculpture',
        themeId: 'noir',
        spaceId: 'monolith',
        light: {
          mode: 'neon',
          master: 1.15,
          keyIntensity: 2.1,
          rimIntensity: 1.4,
          rimColor: '#66aaff',
          accentIntensity: 2.6,
          accentColor: '#ff6ab0',
          ambient: 0.2,
          fillIntensity: 0.15,
        },
        staging: { backdrop: true, backdropColor: '#1a1a20', floorSheen: 0.35, shadowCatcher: true },
        quality: 'high',
      }),
      B({
        id: 'lit-clamshell',
        label: 'Clamshell Beauty',
        blurb: 'High soft key + under fill. Portrait / beauty standard.',
        envId: 'sculpture',
        themeId: 'softbox',
        spaceId: 'lightbox',
        light: {
          mode: 'beauty',
          master: 1.1,
          keyIntensity: 2.3,
          keyElevation: 58,
          keyAzimuth: 0,
          fillIntensity: 1.5,
          topIntensity: 1.1,
          softboxIntensity: 1.4,
          rimIntensity: 0.35,
          ambient: 0.5,
        },
        staging: { plinth: true, plinthHeight: 0.3, turntable: false, shadowCatcher: true },
        quality: 'high',
      }),
      B({
        id: 'lit-warm-cool',
        label: 'Warm / Cool Cross',
        blurb: 'Amber key vs teal fill — cinematic complementary gels.',
        envId: 'sculpture',
        themeId: 'noir',
        spaceId: 'cyclo',
        light: {
          mode: 'studio',
          master: 1.15,
          keyIntensity: 2.8,
          keyColor: '#ffb347',
          keyAzimuth: -35,
          fillIntensity: 0.9,
          fillColor: '#4ecdc4',
          rimIntensity: 0.7,
          rimColor: '#ffe0a0',
          softboxIntensity: 1.2,
          softboxColor: '#ffe8c8',
          softboxColorR: '#c8f0ea',
          gelSaturation: 1.15,
          ambient: 0.3,
        },
        staging: { shadowCatcher: true, floorSheen: 0.15 },
        quality: 'high',
      }),
      B({
        id: 'lit-magenta-cyan',
        label: 'Magenta / Cyan',
        blurb: 'Split softbox gels + magenta rim. Fashion editorial.',
        envId: 'sculpture',
        themeId: 'fashion-gray',
        spaceId: 'monolith',
        light: {
          mode: 'softbox',
          master: 1.1,
          keyIntensity: 1.2,
          keyColor: '#ffd6e8',
          fillColor: '#b8f0ff',
          rimIntensity: 1.5,
          rimColor: '#ff2d95',
          softboxIntensity: 2.0,
          softboxColor: '#ff2d95',
          softboxColorR: '#00e5ff',
          accentIntensity: 1.4,
          accentColor: '#ff2d95',
          gelSaturation: 1.25,
          ambient: 0.25,
        },
        staging: { plinth: true, plinthHeight: 0.35, shadowCatcher: true },
        quality: 'high',
      }),
      B({
        id: 'lit-club-rgb',
        label: 'Club RGB',
        blurb: 'Spinning RGB color ring + magenta accent. Night look.',
        envId: 'sculpture',
        themeId: 'noir',
        spaceId: 'atmos',
        light: {
          mode: 'neon',
          master: 1.2,
          keyIntensity: 1.4,
          fillIntensity: 0.2,
          rimIntensity: 0.9,
          rimColor: '#ff00cc',
          accentIntensity: 1.6,
          accentColor: '#ff00cc',
          ambient: 0.18,
          colorRing: true,
          colorRingIntensity: 2.1,
          colorRingCount: 4,
          colorRingSpeed: 7,
          colorRingColors: ['#ff0040', '#00ff88', '#0088ff', '#ff00cc'],
          gelSaturation: 1.35,
        },
        staging: { shadowCatcher: true, floorSheen: 0.4 },
        quality: 'high',
      }),
      B({
        id: 'lit-prism-wash',
        label: 'Prism Wash',
        blurb: 'Static six-color ring — rainbow product wash.',
        envId: 'sculpture',
        themeId: 'pure-white',
        spaceId: 'cyclo',
        light: {
          mode: 'product',
          master: 1.05,
          keyIntensity: 1.5,
          fillIntensity: 0.3,
          ambient: 0.28,
          colorRing: true,
          colorRingIntensity: 1.9,
          colorRingCount: 6,
          colorRingSpeed: 0,
          colorRingHeight: 0.4,
          colorRingRadius: 0.6,
          gelSaturation: 1.2,
        },
        staging: {
          plinth: true,
          plinthHeight: 0.3,
          turntable: true,
          turntableSpeed: 4,
          shadowCatcher: true,
        },
        quality: 'high',
      }),
      B({
        id: 'lit-duo-chrome',
        label: 'Duo Chrome',
        blurb: 'Orange / blue split softboxes — graphic product look.',
        envId: 'stage',
        themeId: 'concrete',
        spaceId: 'lightbox',
        light: {
          mode: 'softbox',
          master: 1.1,
          softboxIntensity: 2.5,
          softboxSize: 1.35,
          softboxColor: '#ff7a18',
          softboxColorR: '#1b9aaa',
          keyIntensity: 1.0,
          keyColor: '#fff0e0',
          rimIntensity: 0.7,
          rimColor: '#1b9aaa',
          accentIntensity: 0.9,
          accentColor: '#ff7a18',
          gelSaturation: 1.2,
          ambient: 0.3,
        },
        staging: { shadowCatcher: true, floorSheen: 0.2 },
        quality: 'high',
      }),
    ],
  },
  {
    id: 'minimal',
    label: 'Minimal',
    blurb: 'The room itself is the design.',
    presets: [
      B({
        id: 'void',
        label: 'Void',
        blurb: 'Empty studio chamber, tight composition.',
        envId: 'void',
        themeId: 'studio',
        params: { fov: 30, margin: 0.04, radius: 1.0 },
      }),
      B({
        id: 'shadow-box',
        label: 'Shadow Box',
        blurb: 'Dark empty enclosure — indirect light does the work.',
        envId: 'void',
        themeId: 'noir',
        params: { lightIntensity: 1.2, ssgiIntensity: 1.6, exposure: 1.2, radius: 1.6 },
      }),
      B({
        id: 'cyclorama',
        label: 'Cyclorama',
        blurb: 'Maximum cove radius — photography infinity wall.',
        envId: 'void',
        themeId: 'limestone',
        params: { radius: 2, rearInset: 0, roughness: 0.98, fov: 38, margin: 0.03 },
      }),
    ],
  },
];

export const ALL_BUILTIN: Preset[] = COLLECTIONS.flatMap((c) => c.presets);
