import { createContext, useContext, useEffect, useMemo, useRef, useSyncExternalStore, type MutableRefObject, type PropsWithChildren } from 'react'
import { ArtinosRuntime, createArtinosRuntime, type ParameterDefinition, type ParameterValue } from '../core'
const RuntimeContext=createContext<ArtinosRuntime|null>(null)
export function ArtinosRuntimeProvider({children,runtime}:PropsWithChildren<{runtime?:ArtinosRuntime}>){const value=useMemo(()=>runtime??createArtinosRuntime(),[runtime]);return <RuntimeContext.Provider value={value}>{children}</RuntimeContext.Provider>}
export function useArtinosRuntime(){const runtime=useContext(RuntimeContext);if(!runtime)throw new Error('useArtinosRuntime must be used inside ArtinosRuntimeProvider');return runtime}
/** UI/base-value subscription. Runtime modulation never causes this hook to render. */
export function useParameter<T extends ParameterValue>(definition:ParameterDefinition<T>):[T,(value:T)=>void]{const runtime=useArtinosRuntime();runtime.parameters.ensure(definition);const value=useSyncExternalStore(fn=>runtime.parameters.subscribeBase(definition.id,fn),()=>runtime.parameters.getBase<T>(definition.id)??definition.defaultValue,()=>definition.defaultValue);return[value,next=>runtime.setParameter(definition.id,next,`Set ${definition.label??definition.id}`)]}
/** Explicit, rate-limited bridge for React components that must reflect resolved values. */
export function useResolvedParameter<T extends ParameterValue>(definition:ParameterDefinition<T>,intervalMs=100):T{const runtime=useArtinosRuntime();runtime.parameters.ensure(definition);return useSyncExternalStore(fn=>runtime.parameters.subscribeResolvedSnapshot(definition.id,fn,intervalMs),()=>runtime.parameters.getResolved<T>(definition.id)??definition.defaultValue,()=>definition.defaultValue)}
/** Direct resolved-value bridge for frame consumers that must not trigger React renders. */
export function useResolvedParameterRef<T extends ParameterValue>(id:string,fallback:T):MutableRefObject<T>{const runtime=useArtinosRuntime();const value=useRef(runtime.parameters.getResolved<T>(id)??fallback);useEffect(()=>runtime.parameters.subscribeResolved(id,()=>{value.current=runtime.parameters.getResolved<T>(id)??fallback}),[runtime,id,fallback]);return value}
export function useSignal<T=unknown>(id:string,fallback:T):T{const runtime=useArtinosRuntime();return useSyncExternalStore(fn=>runtime.signals.subscribe(id,()=>fn()),()=>runtime.signals.get<T>(id)??fallback,()=>fallback)}
export function useResource<T=unknown>(id:string):T|undefined{const runtime=useArtinosRuntime();return useSyncExternalStore(runtime.resources.subscribe.bind(runtime.resources),()=>runtime.resources.get<T>(id),()=>undefined)}
export function useQualityState(){const runtime=useArtinosRuntime();return useSyncExternalStore(runtime.quality.subscribe.bind(runtime.quality),runtime.quality.getState.bind(runtime.quality),runtime.quality.getState.bind(runtime.quality))}
export function useTelemetryMetric<T=number|string|boolean>(id:string,fallback:T):T{const runtime=useArtinosRuntime();return useSyncExternalStore(runtime.telemetry.subscribe.bind(runtime.telemetry),()=>runtime.telemetry.get(id)?.value as T??fallback,()=>fallback)}
