import { Backdrop, Environment as DreiEnvironment, Lightformer, Sky } from '@react-three/drei'
import { Color } from 'three'
import { useThree } from '@react-three/fiber'
import { useEffect, useMemo } from 'react'
export type EnvironmentPreset='blank'|'clean'|'neutral'|'studio'|'softbox'|'warehouse'|'gallery'|'adaptive-room'|'hdr'|'sky'|'outdoor'|'sunset'|'night'
import { measureContentBounds, resolveAdaptiveRoom } from './scene-math'
export { measureContentBounds, resolveAdaptiveRoom } from './scene-math'
export interface EnvironmentProps{preset?:EnvironmentPreset;background?:string|boolean;intensity?:number;blur?:number;rotation?:number;hdr?:string;ground?:boolean;groundColor?:string;groundY?:number;fog?:boolean}
function Stars({radius=70,depth=50,factor=4}:{radius?:number;depth?:number;factor?:number}){const positions=useMemo(()=>{const values=new Float32Array(1200*3);for(let i=0;i<1200;i++){const r=radius+Math.random()*depth,theta=Math.random()*Math.PI*2,phi=Math.acos(2*Math.random()-1);values[i*3]=r*Math.sin(phi)*Math.cos(theta);values[i*3+1]=r*Math.cos(phi);values[i*3+2]=r*Math.sin(phi)*Math.sin(theta)}return values},[radius,depth]);return <points><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/></bufferGeometry><pointsMaterial color="#dcecff" size={factor*.018} sizeAttenuation transparent opacity={.85} depthWrite={false}/></points>}
function ProceduralEnvironment({preset,background,intensity,rotation}:{preset:EnvironmentPreset;background:string|boolean;intensity:number;rotation:number}){const warehouse=preset==='warehouse',gallery=preset==='gallery',soft=preset==='softbox';return <DreiEnvironment background={Boolean(background)} resolution={256} environmentIntensity={intensity}><group rotation={[0,rotation,0]}><Lightformer color={soft?'#fff4e8':'#ffffff'} intensity={soft?5:4} position={[0,5,-4]} scale={[soft?8:6,soft?3:2,1]}/><Lightformer color={warehouse?'#9fc4ff':'#d8e8ff'} intensity={warehouse?3:2} position={[-5,1,1]} rotation-y={Math.PI/2} scale={[4,2,1]}/><Lightformer color={gallery?'#ffd6ae':'#ffffff'} intensity={gallery?3:2} position={[5,1,1]} rotation-y={-Math.PI/2} scale={[4,2,1]}/><Lightformer color="#ffffff" intensity={1.25} position={[0,-3,4]} scale={[5,1,1]}/></group></DreiEnvironment>}
export function Environment({preset='studio',background=true,intensity=1,blur=.12,rotation=0,hdr,ground=true,groundColor='#777876',groundY=-1.15}:EnvironmentProps){const scene=useThree((s:any)=>s.scene),viewport=useThree(s=>s.size),room=resolveAdaptiveRoom(measureContentBounds(scene),viewport,groundY);useEffect(()=>{if(typeof background==='string'){const before=scene.background;scene.background=new Color(background);return()=>{scene.background=before}}},[scene,background]);if(preset==='blank')return null;if(preset==='clean')return <><color attach="background" args={[typeof background==='string'?background:'#e7e7e4']}/>{ground&&<GroundPlane color={groundColor} y={groundY}/>}</>;if(preset==='neutral')return <><color attach="background" args={[typeof background==='string'?background:'#202326']}/><ProceduralEnvironment preset={preset} background={false} intensity={intensity} rotation={rotation}/></>;if(preset==='sky'||preset==='outdoor'||preset==='sunset'){const sun=preset==='sunset'?[2,.6,-4]:[4,5,2];return <><Sky sunPosition={sun as [number,number,number]} turbidity={preset==='sunset'?10:8} rayleigh={preset==='sunset'?4:2}/>{preset==='outdoor'&&ground&&<GroundPlane color={groundColor} y={groundY} size={150}/>}</>};if(preset==='night')return <><color attach="background" args={[typeof background==='string'?background:'#02050a']}/><Stars radius={70} depth={50} factor={4}/><ProceduralEnvironment preset={preset} background={false} intensity={intensity*.35} rotation={rotation}/></>;if(preset==='adaptive-room')return <group name="artinos-environment"><ProceduralEnvironment preset={preset} background={false} intensity={intensity} rotation={rotation}/><Backdrop floor={1.3} segments={48} receiveShadow scale={room.scale} position={room.position}><meshStandardMaterial color={typeof background==='string'?background:'#b9b8b4'} roughness={.72}/></Backdrop></group>;if(preset==='hdr'&&hdr)return <DreiEnvironment files={hdr} background={Boolean(background)} backgroundBlurriness={blur} environmentIntensity={intensity} environmentRotation={[0,rotation,0]}/>;return <ProceduralEnvironment preset={preset} background={background} intensity={intensity} rotation={rotation}/>;}
export function GroundPlane({color='#777876',y=-1.15,size=30,roughness=.9,metalness=0}:{color?:string;y?:number;size?:number;roughness?:number;metalness?:number}){return <mesh rotation-x={-Math.PI/2} position-y={y} receiveShadow><planeGeometry args={[size,size]}/><meshStandardMaterial color={color} roughness={roughness} metalness={metalness}/></mesh>}
