import { useEffect } from 'react'
import { useThree } from '@react-three/fiber'
import { useArtinosRuntime } from '@artinos/runtime'
import * as THREE from 'three/webgpu'
import { resolveDprRange } from './scene-math'
export type RenderPreset='fast'|'mobile'|'balanced'|'high'|'ultra'|'cinematic'|'product'|'interactive'|'installation'|'screenshot'
export type ToneMappingName='none'|'linear'|'reinhard'|'cineon'|'aces'|'agx'|'neutral'
export type ShadowMapName='basic'|'pcf'|'pcf-soft'|'vsm'
const tone:Record<ToneMappingName,number>={none:THREE.NoToneMapping,linear:THREE.LinearToneMapping,reinhard:THREE.ReinhardToneMapping,cineon:THREE.CineonToneMapping,aces:THREE.ACESFilmicToneMapping,agx:(THREE as any).AgXToneMapping??THREE.ACESFilmicToneMapping,neutral:(THREE as any).NeutralToneMapping??THREE.ACESFilmicToneMapping}
const shadowType:Record<ShadowMapName,number>={basic:THREE.BasicShadowMap,pcf:THREE.PCFShadowMap,'pcf-soft':THREE.PCFSoftShadowMap,vsm:THREE.VSMShadowMap}
export const renderPresets:Record<RenderPreset,{dpr:[number,number];toneMapping:ToneMappingName;shadows:boolean;shadowMap:ShadowMapName}>={fast:{dpr:[.65,1],toneMapping:'agx',shadows:false,shadowMap:'basic'},mobile:{dpr:[.75,1.25],toneMapping:'agx',shadows:true,shadowMap:'pcf'},balanced:{dpr:[1,1.5],toneMapping:'agx',shadows:true,shadowMap:'pcf-soft'},high:{dpr:[1,2],toneMapping:'agx',shadows:true,shadowMap:'pcf-soft'},ultra:{dpr:[1,2.5],toneMapping:'agx',shadows:true,shadowMap:'vsm'},cinematic:{dpr:[1,2],toneMapping:'agx',shadows:true,shadowMap:'vsm'},product:{dpr:[1,2.5],toneMapping:'neutral',shadows:true,shadowMap:'vsm'},interactive:{dpr:[.8,1.5],toneMapping:'agx',shadows:true,shadowMap:'pcf-soft'},installation:{dpr:[.75,1.5],toneMapping:'agx',shadows:true,shadowMap:'pcf'},screenshot:{dpr:[2,4],toneMapping:'agx',shadows:true,shadowMap:'vsm'}}
export const resolvePresetDpr=(preset:RenderPreset,scalar:number)=>resolveDprRange(renderPresets[preset].dpr,scalar)
export function RenderSettings({preset='high',exposure=1,shadows,toneMapping,shadowMap,clearAlpha=1,outputColorSpace='srgb'}:{preset?:RenderPreset;exposure?:number;shadows?:boolean;toneMapping?:ToneMappingName;shadowMap?:ShadowMapName;clearAlpha?:number;outputColorSpace?:'srgb'|'linear-srgb'}){const runtime=useArtinosRuntime(),renderer=useThree((s:any)=>s.renderer??s.gl),setDpr=useThree((s:any)=>s.setDpr),p=renderPresets[preset];useEffect(()=>{renderer.toneMappingExposure=exposure;renderer.toneMapping=tone[toneMapping??p.toneMapping];renderer.outputColorSpace=outputColorSpace==='linear-srgb'?THREE.LinearSRGBColorSpace:THREE.SRGBColorSpace;renderer.setClearAlpha?.(clearAlpha);if(renderer.shadowMap){renderer.shadowMap.enabled=shadows??p.shadows;renderer.shadowMap.type=shadowType[shadowMap??p.shadowMap]}},[renderer,exposure,shadows,toneMapping,shadowMap,clearAlpha,outputColorSpace,p]);useEffect(()=>runtime.quality.register('scene.render.dpr',quality=>{const dpr=resolvePresetDpr(preset,quality.scalar);setDpr(dpr);runtime.signals.set('render.dpr',dpr);runtime.signals.set('render.dprRange',p.dpr);runtime.telemetry.set('renderer.dpr',dpr,{group:'renderer'});runtime.telemetry.set('render.preset.dprRange',p.dpr.join('–'),{group:'renderer'})}),[runtime,setDpr,p,preset]);return null}
